countries = {'AD': u'Andorra',
             'AE': u'United Arab Emirates',
             'AF': u'Afghanistan',
             'AG': u'Antigua and Barbuda',
             'AI': u'Anguilla',
             'AL': u'Albania',
             'AM': u'Armenia',
             'AO': u'Angola',
             'AQ': u'Antarctica',
             'AR': u'Argentina',
             'AS': u'American Samoa',
             'AT': u'Austria',
             'AU': u'Australia',
             'AW': u'Aruba',
             'AX': u'Aland Islands',
             'AZ': u'Azerbaijan',
             'BA': u'Bosnia and Herzegovina',
             'BB': u'Barbados',
             'BD': u'Bangladesh',
             'BE': u'Belgium',
             'BF': u'Burkina Faso',
             'BG': u'Bulgaria',
             'BH': u'Bahrain',
             'BI': u'Burundi',
             'BJ': u'Benin',
             'BL': u'Saint Barthelemy',
             'BM': u'Bermuda',
             'BN': u'Brunei Darussalam',
             'BO': u'Bolivia, Plurinational State of',
             'BQ': u'Bonaire, Sint Eustatius and Saba',
             'BR': u'Brazil',
             'BS': u'Bahamas',
             'BT': u'Bhutan',
             'BV': u'Bouvet Island',
             'BW': u'Botswana',
             'BY': u'Belarus',
             'BZ': u'Belize',
             'CA': u'Canada',
             'CC': u'Cocos (Keeling Islands)',
             'CD': u'Congo, The Democratic Republic of the',
             'CF': u'Central African Republic',
             'CG': u'Congo',
             'CH': u'Switzerland',
             'CI': u"Cote D'ivoire",
             'CK': u'Cook Islands',
             'CL': u'Chile',
             'CM': u'Cameroon',
             'CN': u'China',
             'CO': u'Colombia',
             'CR': u'Costa Rica',
             'CU': u'Cuba',
             'CV': u'Cape Verde',
             'CW': u'Curaeao',
             'CX': u'Christmas Island',
             'CY': u'Cyprus',
             'CZ': u'Czech Republic',
             'DE': u'Germany',
             'DJ': u'Djibouti',
             'DK': u'Denmark',
             'DM': u'Dominica',
             'DO': u'Dominican Republic',
             'DZ': u'Algeria',
             'EC': u'Ecuador',
             'EE': u'Estonia',
             'EG': u'Egypt',
             'EH': u'Western Sahara',
             'ER': u'Eritrea',
             'ES': u'Spain',
             'ET': u'Ethiopia',
             'FI': u'Finland',
             'FJ': u'Fiji',
             'FK': u'Falkland Islands (Malvinas)',
             'FM': u'Micronesia, Federated States of',
             'FO': u'Faroe Islands',
             'FR': u'France',
             'GA': u'Gabon',
             'GB': u'United Kingdom',
             'GD': u'Grenada',
             'GE': u'Georgia',
             'GF': u'French Guiana',
             'GG': u'Guernsey',
             'GH': u'Ghana',
             'GI': u'Gibraltar',
             'GL': u'Greenland',
             'GM': u'Gambia',
             'GN': u'Guinea',
             'GP': u'Guadeloupe',
             'GQ': u'Equatorial Guinea',
             'GR': u'Greece',
             'GS': u'South Georgia and the South Sandwich Islands',
             'GT': u'Guatemala',
             'GU': u'Guam',
             'GW': u'Guinea-bissau',
             'GY': u'Guyana',
             'HK': u'Hong Kong',
             'HM': u'Heard Island and McDonald Islands',
             'HN': u'Honduras',
             'HR': u'Croatia',
             'HT': u'Haiti',
             'HU': u'Hungary',
             'ID': u'Indonesia',
             'IE': u'Ireland',
             'IL': u'Israel',
             'IM': u'Isle of Man',
             'IN': u'India',
             'IO': u'British Indian Ocean Territory',
             'IQ': u'Iraq',
             'IR': u'Iran, Islamic Republic of',
             'IS': u'Iceland',
             'IT': u'Italy',
             'JE': u'Jersey',
             'JM': u'Jamaica',
             'JO': u'Jordan',
             'JP': u'Japan',
             'KE': u'Kenya',
             'KG': u'Kyrgyzstan',
             'KH': u'Cambodia',
             'KI': u'Kiribati',
             'KM': u'Comoros',
             'KN': u'Saint Kitts and Nevis',
             'KP': u"Korea, Democratic People's Republic of",
             'KR': u'Korea, Republic of',
             'KW': u'Kuwait',
             'KY': u'Cayman Islands',
             'KZ': u'Kazakhstan',
             'LA': u"Lao People's Democratic Republic",
             'LB': u'Lebanon',
             'LC': u'Saint Lucia',
             'LI': u'Liechtenstein',
             'LK': u'Sri Lanka',
             'LR': u'Liberia',
             'LS': u'Lesotho',
             'LT': u'Lithuania',
             'LU': u'Luxembourg',
             'LV': u'Latvia',
             'LY': u'Libya',
             'MA': u'Morocco',
             'MC': u'Monaco',
             'MD': u'Moldova, Republic of',
             'ME': u'Montenegro',
             'MF': u'Saint Martin (French Part)',
             'MG': u'Madagascar',
             'MH': u'Marshall Islands',
             'MK': u'Macedonia, The Former Yugoslav Republic of',
             'ML': u'Mali',
             'MM': u'Myanmar',
             'MN': u'Mongolia',
             'MO': u'Macao',
             'MP': u'Northern Mariana Islands',
             'MQ': u'Martinique',
             'MR': u'Mauritania',
             'MS': u'Montserrat',
             'MT': u'Malta',
             'MU': u'Mauritius',
             'MV': u'Maldives',
             'MW': u'Malawi',
             'MX': u'Mexico',
             'MY': u'Malaysia',
             'MZ': u'Mozambique',
             'NA': u'Namibia',
             'NC': u'New Caledonia',
             'NE': u'Niger',
             'NF': u'Norfolk Island',
             'NG': u'Nigeria',
             'NI': u'Nicaragua',
             'NL': u'Netherlands',
             'NO': u'Norway',
             'NP': u'Nepal',
             'NR': u'Nauru',
             'NU': u'Niue',
             'NZ': u'New Zealand',
             'OM': u'Oman',
             'PA': u'Panama',
             'PE': u'Peru',
             'PF': u'French Polynesia',
             'PG': u'Papua New Guinea',
             'PH': u'Philippines',
             'PK': u'Pakistan',
             'PL': u'Poland',
             'PM': u'Saint Pierre and Miquelon',
             'PN': u'Pitcairn',
             'PR': u'Puerto Rico',
             'PS': u'Palestinian Territory, Occupied',
             'PT': u'Portugal',
             'PW': u'Palau',
             'PY': u'Paraguay',
             'QA': u'Qatar',
             'RE': u'Reunion',
             'RO': u'Romania',
             'RS': u'Serbia',
             'RU': u'Russian Federation',
             'RW': u'Rwanda',
             'SA': u'Saudi Arabia',
             'SB': u'Solomon Islands',
             'SC': u'Seychelles',
             'SD': u'Sudan',
             'SE': u'Sweden',
             'SG': u'Singapore',
             'SH': u'Saint Helena, Ascension and Tristan Da Cunha',
             'SI': u'Slovenia',
             'SJ': u'Svalbard and Jan Mayen',
             'SK': u'Slovakia',
             'SL': u'Sierra Leone',
             'SM': u'San Marino',
             'SN': u'Senegal',
             'SO': u'Somalia',
             'SR': u'Suriname',
             'SS': u'South Sudan',
             'ST': u'Sao Tome and Principe',
             'SV': u'El Salvador',
             'SX': u'Sint Maarten (Dutch Part)',
             'SY': u'Syrian Arab Republic',
             'SZ': u'Swaziland',
             'TC': u'Turks and Caicos Islands',
             'TD': u'Chad',
             'TF': u'French Southern Territories',
             'TG': u'Togo',
             'TH': u'Thailand',
             'TJ': u'Tajikistan',
             'TK': u'Tokelau',
             'TL': u'Timor-leste',
             'TM': u'Turkmenistan',
             'TN': u'Tunisia',
             'TO': u'Tonga',
             'TR': u'Turkey',
             'TT': u'Trinidad and Tobago',
             'TV': u'Tuvalu',
             'TW': u'Taiwan, Province of China',
             'TZ': u'Tanzania, United Republic of',
             'UA': u'Ukraine',
             'UG': u'Uganda',
             'UM': u'United States Minor Outlying Islands',
             'US': u'United States',
             'UY': u'Uruguay',
             'UZ': u'Uzbekistan',
             'VA': u'Holy See (Vatican City State)',
             'VC': u'Saint Vincent and the Grenadines',
             'VE': u'Venezuela, Bolivarian Republic of',
             'VG': u'Virgin Islands, British',
             'VI': u'Virgin Islands, U.S.',
             'VN': u'Vietnam',
             'VU': u'Vanuatu',
             'WF': u'Wallis and Futuna',
             'WS': u'Samoa',
             'YE': u'Yemen',
             'YT': u'Mayotte',
             'ZA': u'South Africa',
             'ZM': u'Zambia',
             'ZW': u'Zimbabwe'}
