all=[
("Afghanistan,Dari","prs","AF"),
("Afghanistan","Pashto","ps","AF"),
("Albania","Albanian","sq","AL"),
("Algeria","Tamazight (Latin)","tzm","DZ"),
("Armenia","Armenian","hy","AM"),
("Azerbaijan","Azeri (Cyrillic)","az","AZ"),
("Bangladesh","Bengali","bn","BD"),
("Belarus","Belarusian","be","BY"),
("Bosnia and Herzegovina","Bosnian (Cyrillic)","bs","BA"),
("Brazil","Portuguese","pt","BR"),
("Bulgaria","Bulgarian","bg","BG"),
("Cambodia","Khmer","km","KH"),
("Canada","Inuktitut (Latin)","iu","CA"),
("Canada","Mohawk","moh","CA"),
("Chile","Mapudungun","arn","CL"),
("Croatia","Croatian","hr","HR"),
("Czech Republic","Czech","cs","CZ"),
("Denmark","Danish","da","DK"),
("Egypt","Arabic","ar","EG"),
("Estonia","Estonian","et","EE"),
("Ethiopia","Amharic","am","ET"),
("Faroe Islands","Faroese","fo","FO"),
("Finland","Finnish","fi","FI"),
("Finland","Sami (Inari)","smn","FI"),
("Finland","Sami (Skolt)","sms","FI"),
("France","Alsatian","gsw","FR"),
("France","Breton","br","FR"),
("France","Corsican","co","FR"),
("France","French","fr","FR"),
("France","Occitan","oc","FR"),
("Georgia","Georgian","ka","GE"),
("Germany","German","de","DE"),
("Greece","Greek","el","GR"),
("Greenland","Greenlandic","kl","GL"),
("Hong Kong"," Chinese (Traditional) Legacy","zh","HK"),
("Hungary","Hungarian","hu","HU"),
("Iceland","Icelandic","is","IS"),
("India","Assamese","as","IN"),
("India","Gujarati","gu","IN"),
("India","Hindi","hi","IN"),
("India","Kannada","kn","IN"),
("India","Konkani","kok","IN"),
("India","Malayalam","ml","IN"),
("India","Marathi","mr","IN"),
("India","Oriya","or","IN"),
("India","Punjabi","pa","IN"),
("India","Sanskrit","sa","IN"),
("India","Tamil","ta","IN"),
("India","Telugu","te","IN"),
("Indonesia","Indonesian","id","ID"),
("Iran","Persian","fa","IR"),
("Ireland","Irish","ga","IE"),
("Pakistan","Urdu","ur","PK"),
("Israel","Hebrew","he","IL"),
("Italy","Italian","it","IT"),
("Japan","Japanese","ja","JP"),
("Jordan","Arabic","ar","JO"),
("Kazakhstan","Kazakh","kk","KZ"),
("Kenya","Kiswahili","sw","KE"),
("Korea","Korean","ko","KR"),
("Kuwait","Arabic","ar","KW"),
("Kyrgyzstan","Kyrgyz","ky","KG"),
("Lao"," Lao","lo","LA"),
("Latvia","Latvian","lv","LV"),
("Lebanon","Arabic","ar","LB"),
("Libya","Arabic","ar","LY"),
("Liechtenstein","German","de","LI"),
("Lithuania","Lithuanian","lt","LT"),
("Luxembourg","Luxembourgish","lb","LU"),
("Macao"," Chinese (Traditional) Legacy","zh","MO"),
("Macedonia"," Macedonian (FYROM)","mk","MK"),
("Malaysia","Malay","ms","MY"),
("Maldives","Divehi","dv","MV"),
("Malta","Maltese","mt","MT"),
("Mongolia","Mongolian (Cyrillic)","mn","MN"),
("Morocco","Arabic","ar","MA"),
("Nepal","Nepali","ne","NP"),
("Netherlands","Dutch","nl","NL"),
("Netherlands","Frisian","fy","NL"),
("New Zealand","Maori","mi","NZ"),
("Nigeria","Hausa (Latin)","ha","NG"),
("Nigeria","Igbo","ig","NG"),
("Nigeria","Yoruba","yo","NG"),
("Norway","Norwegian (Bokmal)","nb","NO"),
("Norway","Norwegian (Nynorsk)","nn","NO"),
("Oman","Arabic","ar","OM"),
("China"," Chinese (Simplified) Legacy","zh","CN"),
("China"," Tibetan","bo","CN"),
("China"," Uyghur","ug","CN"),
("China"," Yi","ii","CN"),
("Peru","Quechua","quz","PE"),
("Philippines","Filipino","fil","PH"),
("Poland","Polish","pl","PL"),
("Qatar","Arabic","ar","QA"),
("Romania","Romanian","ro","RO"),
("Russia","Bashkir","ba","RU"),
("Russia","Russian","ru","RU"),
("Russia","Tatar","tt","RU"),
("Russia","Yakut","sah","RU"),
("Rwanda","Kinyarwanda","rw","RW"),
("Saudi Arabia","Arabic","ar","SA"),
("Senegal","Wolof","wo","SN"),
("Serbia","Serbian (Cyrillic)","sr","RS"),
("Singapore","Chinese (Simplified) Legacy","zh","SG"),
("Slovakia","Slovak","sk","SK"),
("Slovenia","Slovenian","sl","SI"),
("South Africa","Afrikaans","af","ZA"),
("South Africa","isiXhosa","xh","ZA"),
("South Africa","isiZulu","zu","ZA"),
("South Africa","Sesotho sa Leboa","nso","ZA"),
("South Africa","Setswana","tn","ZA"),
("Spain","Basque","eu","ES"),
("Spain","Catalan","ca","ES"),
("Spain","Galician","gl","ES"),
("Spain","Spanish","es","ES"),
("Sri Lanka","Sinhala","si","LK"),
("Sweden","Sami (Lule)","smj","SE"),
("Sweden","Sami (Southern)","sma","SE"),
("Sweden","Swedish","sv","SE"),
("Switzerland","Romansh","rm","CH"),
("Syria","Syriac","syr","SY"),
("Taiwan","Chinese (Traditional) Legacy","zh","TW"),
("Tajikistan","Tajik (Cyrillic)","tg","TJ"),
("Thailand","Thai","th","TH"),
("Tunisia","Arabic","ar","TN"),
("Turkey","Turkish","tr","TR"),
("Turkmenistan","Turkmen","tk","TM"),
("United Arab Emirates"," Arabic","ar","AE"),
("Ukraine","Ukrainian","uk","UA"),
("United Kingdom","Scottish Gaelic","gd","GB"),
("United Kingdom","Welsh","cy","GB"),
("United States of America"," English","en","US"),
("Uzbekistan","Uzbek (Cyrillic)","uz","UZ"),
("Vietnam","Vietnamese","vi","VN"),
("Yemen","Arabic","ar","YE")
]